# -*- coding: utf-8 -*-
"""Tugas AED

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11yZftHoRwr1kK14H9IzCy5CKSXLt9t6w
"""

print("Delita Nur Hasanah G1401221018")

import pandas as pd
from google.colab import drive
drive.mount('/content/drive')

data = pd.read_excel("/content/drive/My Drive/Colab Notebooks/CUACA.xlsx")
data

# @title KELEMBABAN vs TEMPERATUR

from matplotlib import pyplot as plt
data.plot(kind='scatter', x='KELEMBABAN', y='TEMPERATUR', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

# @title TEMPERATUR vs MATAHARI

from matplotlib import pyplot as plt
data.plot(kind='scatter', x='TEMPERATUR', y='MATAHARI', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

# @title TEMPERATUR

from matplotlib import pyplot as plt
data['TEMPERATUR'].plot(kind='line', figsize=(8, 4), title='TEMPERATUR')
plt.gca().spines[['top', 'right']].set_visible(False)

# @title KELEMBABAN

from matplotlib import pyplot as plt
data['KELEMBABAN'].plot(kind='line', figsize=(8, 4), title='KELEMBABAN')
plt.gca().spines[['top', 'right']].set_visible(False)